SELECT TOP (1000) [CourseID]
      ,[CourseName]
      ,[CourseRegistration]
      ,[Course_CreditHour]
      ,[Course_Professor]
      ,[Course_Supervisor]
      ,[Student_RollNo]
      ,[Student_Name]
      ,[Student_Department]
      ,[Student_Shift]
      ,[Student_Registration]
      ,[Student_CGPA]
      ,[Student_Gender]
      ,[Student_Program]
      ,[Student_Section]
  FROM [CourseManagementSystem].[dbo].[Course]
