//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseRegistration { get; set; }
        public Nullable<int> Course_CreditHour { get; set; }
        public string Course_Professor { get; set; }
        public string Course_Supervisor { get; set; }
        public string Student_RollNo { get; set; }
        public string Student_Name { get; set; }
        public string Student_Department { get; set; }
        public string Student_Shift { get; set; }
        public string Student_Registration { get; set; }
        public Nullable<double> Student_CGPA { get; set; }
        public string Student_Gender { get; set; }
        public string Student_Program { get; set; }
        public string Student_Section { get; set; }
    }
}
